### ISSUE TITLE
DDNS: The SecretId is not found, please ensure that your SecretId is correct.

### ISSUE THREAD

**Issue by cecnet** [vibbow/routeros-ddns-script#1]
阿里正常，腾讯的不行，确认id和key是对的，在其他脚本能更新成功。

**Comment by vibbow** [comment]
我这里测试没问题。

你可以检查下：
是否复制了不可见字符
access token是否授予了所有必须的权限

**Comment by cecnet** [comment]
谢谢，问题解决了。
是我用错api了，腾讯和dnspod的api是不同的，你这里用的是腾讯api，另一个脚本用的是dnspod的api。
